FROM ubuntu:20.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    jq \
    wget \
    vim \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN wget --no-check-certificate https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
