FROM ubuntu:20.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    jq \
    wget \
    vim \
    python3.8 \
    python3-pip \
    python3.8-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install yq